noise: True  # specify if simulation should be run with or without noise
sampling_rate: 5.  # sampling rate in GHz used internally in the simulation.
speedup:
  minimum_weight_cut: 1.e-5
  delta_C_cut: 0.698  # 40 degree
propagation:
  ice_model: southpole_2015
  attenuation_model: SP1
  n_reflections: 1
signal:
  model: Alvarez2009 # add hadronic only
  shower_type: had # optional argument to only simulate certain shower types. Arguments can be "had" or "em".
  polarization: auto # can be either 'auto' or 'custom'
trigger:
  noise_temperature: 250  # in Kelvin
weights:
  weight_mode: core_mantle_crust # core_mantle_crust: use the three
  #layer earth model, which considers the different densities of the
  #core, mantle and crust. simple: use the simple earth model, which
  #apply a constant earth density
